version: '3.4'

services:
  rabbit-mq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - micro-network

  zipkin:
    image: openzipkin/zipkin:2.23.2
    restart: always
    ports:
      - 9411:9411
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest/rabbit-mq:5672
    networks:
      - micro-network

  cambio-db:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - TZ=America/Sao_Paulo
      - POSTGRES_DB=cambio_service
    volumes:
      - ./initcambiodb.sql:/docker-entrypoint-initdb.d/init.sql
    #  - /opt/database:/var/lib/postgresql/data
    networks:
      - micro-network

  book-db:
    image: postgres:latest
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - TZ=America/Sao_Paulo
      - POSTGRES_DB=book_service
    #volumes:
    #  - /opt/database:/var/lib/postgresql/data
    networks:
      - micro-network

  naming-server:
    image: thiagocesar1/namingserver:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - micro-network

  api-gateway:
    image: thiagocesar1/apigateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      RABBIT_URI: amqp://guest:guest/rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - micro-network

  cambio-service:
    image: thiagocesar1/cambioservice:0.0.1-SNAPSHOT
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - cambio-db
      - rabbit-mq
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      SPRING.DATASOURCE.URL: jdbc:postgresql://cambio-db:5432/cambio_service?useSSL=false&enableTLSProtocols=TLSv1.2&serverTimezone=UTC
      SPRING.FLYWAY.URL: jdbc:postgresql://cambio-db:5432/cambio_service?useSSL=false&enableTLSProtocols=TLSv1.2&serverTimezone=UTC
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      RABBIT_URI: amqp://guest:guest/rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - micro-network

  book-service:
    image: thiagocesar1/bookservice:0.0.1-SNAPSHOT
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - book-db
      - rabbit-mq
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      SPRING.DATASOURCE.URL: jdbc:postgresql://book-db:5432/book_service?useSSL=false&enableTLSProtocols=TLSv1.2&serverTimezone=UTC
      SPRING.FLYWAY.URL: jdbc:postgresql://book-db:5432/book_service?useSSL=false&enableTLSProtocols=TLSv1.2&serverTimezone=UTC
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      FEIGN.CLIENT.URL.GATEWAYURL: http://api-gateway:8765/
      RABBIT_URI: amqp://guest:guest/rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - micro-network
networks:
  micro-network:
    driver: bridge
