name: CI Dockerhub

on: [push]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Login Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: '11'
          distribution: 'zulu'
          
      - name: Build Eureka Naming Server
        working-directory: ./naming-server
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Api Gateway
        working-directory: ./api-gateway
        run: mvn spring-boot:build-image -DskipTests
      
      - name: Build Cambio Service
        working-directory: ./cambio-service
        run: mvn spring-boot:build-image -DskipTests
      
      - name: Build Book Service
        working-directory: ./book-service
        run: mvn spring-boot:build-image -DskipTests
      
      - name: Push to Docker Hub
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/naming-server:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/naming-server:${{ github.run_id }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/api-gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{ github.run_id }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/cambio-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/cambio-service:${{ github.run_id }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/book-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/book-service:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/naming-server:0.0.1-SNAPSHOT
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:0.0.1-SNAPSHOT
          docker push ${{ secrets.DOCKER_USERNAME }}/cambio-service:0.0.1-SNAPSHOT
          docker push ${{ secrets.DOCKER_USERNAME }}/book-service:0.0.1-SNAPSHOT
          
