name: CI Dockerhub

on: [push]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: '11'
          distribution: 'zulu'
          
      - name: Build Eureka Naming Server
        working-directory: ./naming-server
        run: mvn spring-boot:build-image -DskipTests
